# Generated by Django 4.2.28 on 2026-09-18 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_num', models.IntegerField()),
                ('category', models.CharField(choices=[('DSWR', 'DSWR'), ('DLBZ', 'DLBZ'), ('SRGN', 'SRGN'), ('FRBD', 'FRBD'), ('GZBD', 'GZBD'), ('GALI', 'GALI')], max_length=10)),
                ('number', models.IntegerField()),
            ],
            options={
                'ordering': ['index_num'],
                'unique_together': {('index_num', 'category')},
            },
        ),
    ]
