# Generated by Django 4.2.28 on 2026-02-28 10:13

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookbrief', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookSave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'bookbrief_book_save',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'db_table': 'bookbrief_category',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'bookbrief_chapter',
                'ordering': ['summary', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'bookbrief_comment',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('summary', 'Summary'), ('review', 'Review')], default='summary', max_length=10)),
                ('reason', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'bookbrief_report',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('body', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'bookbrief_review',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_type', models.CharField(choices=[('quick', 'Quick Summary (2–5 min read)'), ('detailed', 'Detailed Summary'), ('chapter_wise', 'Chapter-wise Summary'), ('bullet_points', 'Bullet Point Summary'), ('key_lessons', 'Key Lessons'), ('actionable_insights', 'Actionable Insights')], db_index=True, max_length=20)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('content', models.TextField(help_text='Main summary content with headings and formatting.')),
                ('quick_preview', models.CharField(blank=True, max_length=500)),
                ('key_takeaways', models.TextField(blank=True, help_text='Bullet or point-wise key takeaways.')),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('estimated_reading_minutes', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)])),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('is_public', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Summaries',
                'db_table': 'bookbrief_summary',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SummaryVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField(choices=[(1, 'Like'), (-1, 'Dislike')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'bookbrief_summary_vote',
            },
        ),
        migrations.CreateModel(
            name='UserBookStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('want_to_read', 'Want to Read'), ('reading', 'Reading'), ('read', 'Read')], db_index=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'User book statuses',
                'db_table': 'bookbrief_user_book_status',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='slug',
            field=models.SlugField(blank=True, max_length=350, unique=True),
        ),
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], db_index=True, default='published', max_length=20),
        ),
        migrations.AddField(
            model_name='book',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='book',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_contributor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['slug'], name='bookbrief_b_slug_fdc04d_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['status'], name='bookbrief_b_status_3b686a_idx'),
        ),
        migrations.DeleteModel(
            name='BookSummary',
        ),
        migrations.AddField(
            model_name='userbookstatus',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_statuses', to='bookbrief.book'),
        ),
        migrations.AddField(
            model_name='userbookstatus',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_statuses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='summaryvote',
            name='summary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='bookbrief.summary'),
        ),
        migrations.AddField(
            model_name='summaryvote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summary_votes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='summary',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='bookbrief.book'),
        ),
        migrations.AddField(
            model_name='summary',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='bookbrief.book'),
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='report',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='report',
            name='review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_reports', to='bookbrief.review'),
        ),
        migrations.AddField(
            model_name='report',
            name='summary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='summary_reports', to='bookbrief.summary'),
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='bookbrief.comment'),
        ),
        migrations.AddField(
            model_name='comment',
            name='summary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='bookbrief.summary'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summary_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chapter',
            name='summary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='bookbrief.summary'),
        ),
        migrations.AddField(
            model_name='booksave',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saves', to='bookbrief.book'),
        ),
        migrations.AddField(
            model_name='booksave',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_books', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='bookbrief.category'),
        ),
        migrations.AlterUniqueTogether(
            name='userbookstatus',
            unique_together={('user', 'book')},
        ),
        migrations.AlterUniqueTogether(
            name='summaryvote',
            unique_together={('summary', 'user')},
        ),
        migrations.AddIndex(
            model_name='summary',
            index=models.Index(fields=['book'], name='bookbrief_s_book_id_171234_idx'),
        ),
        migrations.AddIndex(
            model_name='summary',
            index=models.Index(fields=['user'], name='bookbrief_s_user_id_506724_idx'),
        ),
        migrations.AddIndex(
            model_name='summary',
            index=models.Index(fields=['summary_type'], name='bookbrief_s_summary_49e5bd_idx'),
        ),
        migrations.AddIndex(
            model_name='summary',
            index=models.Index(fields=['is_public'], name='bookbrief_s_is_publ_bb7637_idx'),
        ),
        migrations.AddIndex(
            model_name='summary',
            index=models.Index(fields=['is_featured'], name='bookbrief_s_is_feat_7269c5_idx'),
        ),
        migrations.AddIndex(
            model_name='summary',
            index=models.Index(fields=['view_count'], name='bookbrief_s_view_co_f5e225_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('book', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='booksave',
            unique_together={('book', 'user')},
        ),
    ]
