# Generated by Django 4.2.28 on 2026-05-19 05:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='interviews.category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('website', models.URLField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(max_length=150)),
                ('job_description', models.TextField(blank=True)),
                ('interview_date', models.DateField()),
                ('mode', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], default='online', max_length=20)),
                ('result', models.CharField(choices=[('pending', 'Pending'), ('selected', 'Selected'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='pending', max_length=20)),
                ('ctc_offered', models.CharField(blank=True, help_text='e.g., 30 LPA', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('overall_experience', models.TextField(blank=True)),
                ('difficulty_level', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=5)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='interviews.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-interview_date'],
            },
        ),
        migrations.CreateModel(
            name='InterviewRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='e.g., Technical Round 1', max_length=100)),
                ('round_type', models.CharField(choices=[('dsa', 'DSA'), ('system_design', 'System Design'), ('hr', 'HR'), ('devops', 'DevOps'), ('backend', 'Backend'), ('frontend', 'Frontend'), ('machine_coding', 'Machine Coding'), ('managerial', 'Managerial'), ('behavioral', 'Behavioral'), ('other', 'Other')], default='dsa', max_length=30)),
                ('feedback', models.TextField(blank=True)),
                ('my_performance', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=5)),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='interviews.interview')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('question_type', models.CharField(choices=[('theory', 'Theory'), ('hr', 'HR'), ('coding', 'Coding'), ('system_design', 'System Design'), ('scenario', 'Scenario')], default='theory', max_length=20)),
                ('description', models.TextField(help_text='Markdown supported problem statement or question.')),
                ('my_answer', models.TextField(blank=True, help_text='Your personal answer in Markdown.')),
                ('best_answer', models.TextField(blank=True, help_text='Ideal or best answer for reference.')),
                ('short_revision_note', models.TextField(blank=True)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('learning', 'Learning'), ('revised', 'Revised'), ('mastered', 'Mastered')], default='not_started', max_length=20)),
                ('is_favorite', models.BooleanField(default=False)),
                ('source', models.URLField(blank=True, help_text='Link to LeetCode, Article, etc.')),
                ('interview_frequency', models.PositiveIntegerField(default=0, help_text='How often asked')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='interviews.category')),
                ('companies', models.ManyToManyField(blank=True, help_text='Companies that ask this', related_name='questions', to='interviews.company')),
                ('interview_rounds', models.ManyToManyField(blank=True, related_name='asked_questions', to='interviews.interviewround')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(max_length=60, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RevisionTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('next_revision_date', models.DateField(blank=True, null=True)),
                ('last_revised_date', models.DateField(blank=True, null=True)),
                ('revision_streak', models.PositiveIntegerField(default=0)),
                ('ease_factor', models.FloatField(default=2.5, help_text='SuperMemo-2 style ease factor')),
                ('interval_days', models.PositiveIntegerField(default=0)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='revision_tracker', to='interviews.question')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='questions', to='interviews.tag'),
        ),
        migrations.AddField(
            model_name='question',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(help_text='Markdown supported content.')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('is_bookmarked', models.BooleanField(default=False)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('tags', models.ManyToManyField(blank=True, related_name='notes', to='interviews.tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CodingProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('constraints', models.TextField(blank=True)),
                ('examples', models.TextField(blank=True)),
                ('my_solution_code', models.TextField(blank=True)),
                ('optimized_solution_code', models.TextField(blank=True)),
                ('time_complexity', models.CharField(blank=True, max_length=100)),
                ('space_complexity', models.CharField(blank=True, max_length=100)),
                ('language', models.CharField(default='python', max_length=50)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coding_details', to='interviews.question')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
