# Generated by Django 4.2.28 on 2026-05-19 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codingproblem',
            name='my_solution_code',
        ),
        migrations.RemoveField(
            model_name='codingproblem',
            name='optimized_solution_code',
        ),
        migrations.RemoveField(
            model_name='question',
            name='best_answer',
        ),
        migrations.RemoveField(
            model_name='question',
            name='description',
        ),
        migrations.RemoveField(
            model_name='question',
            name='my_answer',
        ),
        migrations.RemoveField(
            model_name='question',
            name='short_revision_note',
        ),
        migrations.CreateModel(
            name='QuestionContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.CharField(choices=[('problem_statement', 'Problem Statement'), ('quick_answer', 'Quick Answer'), ('deep_dive', 'Deep Dive'), ('personal_note', 'Personal Note'), ('beginner_code', 'Beginner Code'), ('optimized_code', 'Optimized Code'), ('production_code', 'Production Code'), ('diagram', 'Diagram'), ('architecture', 'Architecture Note'), ('interview_tip', 'Interview Tip'), ('follow_up', 'Follow-up Question'), ('debugging', 'Debugging Tip'), ('optimization', 'Optimization Note'), ('use_case', 'Use Case'), ('anti_pattern', 'Anti-Pattern'), ('revision_note', 'Revision Note'), ('flashcard', 'Flashcard'), ('cheat_sheet', 'Cheat Sheet')], max_length=30)),
                ('title', models.CharField(blank=True, help_text='Optional section title', max_length=255)),
                ('content', models.TextField(help_text='Markdown content')),
                ('language', models.CharField(blank=True, help_text='e.g. python, javascript (for code)', max_length=50)),
                ('diagram_type', models.CharField(blank=True, help_text='e.g. mermaid (for diagrams)', max_length=50)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_ai_generated', models.BooleanField(default=False)),
                ('metadata_json', models.TextField(blank=True, help_text='JSON serialized metadata')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='interviews.question')),
            ],
            options={
                'ordering': ['display_order', 'created_at'],
            },
        ),
    ]
