# Generated by Django 4.2.28 on 2026-05-24 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0002_remove_codingproblem_my_solution_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questioncontent',
            name='content_roman',
            field=models.TextField(blank=True, help_text='Markdown content in Roman English / Hinglish'),
        ),
    ]
